# Generated by Django 3.0 on 2021-02-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210211_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
