# Generated by Django 3.0 on 2021-02-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
