# Generated by Django 3.0 on 2021-02-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210211_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='end_date',
        ),
    ]
