# Generated by Django 3.0 on 2021-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todo_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='todo',
            name='YorN',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], default='P', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.AutoField(auto_created=True, default=99, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
